version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:30"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
      - "peppers-codebase"
    open-pull-requests-limit: 10
    reviewers: 
      - "nguyentran-se"
